"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, ClipboardPlus, UserRound, X } from "lucide-react";
import AppShell from "@/components/app-shell";
import { createClient } from "@/lib/supabase/client";
import { canRegisterAttendance, continuityOptions, type ContinuityOption } from "./flow-rules";
import "./attendances.css";

type School={id:string;name:string};
type Appointment={id:string;school_id:string;student_id:string;referral_id:string;professional_id:string;starts_at:string;status:string;appointment_type:string;students:{full_name:string;classes:{name:string}|null}|null};
type Attendance={id:string;student_id:string;appointment_id:string;guidance_referrals:string;created_at:string;students:{full_name:string;classes:{name:string}|null}|null;profiles:{full_name:string|null;email:string}|null};
const dateFmt=new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"America/Fortaleza"});

export default function Atendimentos(){
 const [supabase]=useState(()=>createClient());const router=useRouter();const [email,setEmail]=useState("");const [school,setSchool]=useState<School|null>(null);const [role,setRole]=useState("");const [userId,setUserId]=useState("");const [appointments,setAppointments]=useState<Appointment[]>([]);const [records,setRecords]=useState<Attendance[]>([]);const [selected,setSelected]=useState<Appointment|null>(null);const [demand,setDemand]=useState("");const [guidance,setGuidance]=useState("");const [continuity,setContinuity]=useState<ContinuityOption>("conclude");const [returnDate,setReturnDate]=useState("");const [returnTime,setReturnTime]=useState("08:00");const [returnDuration,setReturnDuration]=useState("50");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return;}setEmail(user.email||"");setUserId(user.id);const {data:m}=await supabase.from("school_memberships").select("school_id,role,schools(id,name)").eq("user_id",user.id).eq("active",true).limit(1).single();const raw=m?.schools as unknown;const current=(Array.isArray(raw)?raw[0]:raw) as School|undefined;if(!current)return;setSchool(current);setRole(String(m?.role||""));const [{data:a},{data:r}]=await Promise.all([supabase.from("appointments").select("id,school_id,student_id,referral_id,professional_id,starts_at,status,appointment_type,students(full_name,classes(name))").eq("school_id",current.id).eq("status","scheduled").order("starts_at"),supabase.from("attendances").select("id,student_id,appointment_id,guidance_referrals,created_at,students(full_name,classes(name)),profiles!attendances_author_id_fkey(full_name,email)").eq("school_id",current.id).order("created_at",{ascending:false})]);setAppointments((a||[]) as unknown as Appointment[]);setRecords((r||[]) as unknown as Attendance[]);},[router,supabase]);useEffect(()=>{load();},[load]);
 const canRegister=canRegisterAttendance(role);const eligible=appointments.filter(a=>a.professional_id===userId);
 function close(){setSelected(null);setDemand("");setGuidance("");setContinuity("conclude");setReturnDate("");setReturnTime("08:00");setReturnDuration("50");}
 async function save(ev:FormEvent){ev.preventDefault();if(!school||!selected||!canRegister||!demand.trim()||!guidance.trim())return;if(continuity==="return_scheduled"&&!returnDate)return;setBusy(true);setMessage("");const {data:attendance,error}=await supabase.from("attendances").insert({school_id:school.id,student_id:selected.student_id,referral_id:selected.referral_id,appointment_id:selected.id,author_id:userId,guidance_referrals:guidance.trim()}).select("id").single();if(error||!attendance){setMessage("Não foi possível registrar o atendimento. Confira se o agendamento continua válido.");setBusy(false);return;}const {error:privateError}=await supabase.from("attendance_private_demands").insert({attendance_id:attendance.id,school_id:school.id,author_id:userId,demand:demand.trim()});if(privateError){setMessage("O atendimento foi criado, mas houve falha ao salvar a Escuta Ativa. Não prossiga e comunique a administração do sistema.");setBusy(false);return;}await supabase.from("appointments").update({status:"completed"}).eq("id",selected.id);
  if(continuity==="conclude")await supabase.from("referrals").update({status:"completed"}).eq("id",selected.referral_id);
  if(continuity==="return_pending")await supabase.from("referrals").update({status:"awaiting_schedule"}).eq("id",selected.referral_id);
  if(continuity==="return_scheduled"){const start=new Date(`${returnDate}T${returnTime}:00`),end=new Date(start.getTime()+Number(returnDuration)*60000);const {error:returnError}=await supabase.from("appointments").insert({school_id:school.id,student_id:selected.student_id,referral_id:selected.referral_id,professional_id:userId,starts_at:start.toISOString(),ends_at:end.toISOString(),kind:"Retorno",status:"scheduled",location:"Sala da Equipe Multiprofissional",appointment_type:"return"});if(returnError){await supabase.from("referrals").update({status:"awaiting_schedule"}).eq("id",selected.referral_id);setMessage("Atendimento registrado. O retorno ficou pendente de agendamento porque a data não pôde ser salva.");}else{await supabase.from("referrals").update({status:"scheduled"}).eq("id",selected.referral_id);setMessage("Atendimento registrado e retorno incluído na Agenda.");}}
  if(continuity!=="return_scheduled")setMessage(continuity==="conclude"?"Atendimento registrado e acompanhamento concluído.":"Atendimento registrado. Retorno aguardando definição de data.");close();await load();setBusy(false);
 }
 if(!school)return <main className="loading">Carregando atendimentos…</main>;
 return <AppShell email={email}><header className="attendances-header"><div><p className="eyebrow green">EQUIPE MULTIPROFISSIONAL</p><h1>Atendimentos</h1><p className="muted">O registro de atendimento só pode ser feito a partir de um agendamento.</p></div></header>{message&&<div className="feedback" role="status">{message}</div>}
  {canRegister?<section className="card"><div className="form-heading"><div><h2>Agendamentos aptos para registro</h2><p className="muted">Selecione um compromisso previamente agendado. Aluno e encaminhamento já estão vinculados.</p></div></div>{eligible.length?eligible.map(a=><div className="appointment-item" key={a.id}><div className="appointment-person"><UserRound/><div><strong>{a.students?.full_name}</strong><small>{a.students?.classes?.name||"Sem turma"} · {dateFmt.format(new Date(a.starts_at))} · {a.appointment_type==="return"?"RETORNO":"PRIMEIRO ATENDIMENTO"}</small></div></div><button className="primary-button" onClick={()=>{setSelected(a);setMessage("");window.scrollTo({top:0,behavior:"smooth"});}}><ClipboardPlus/> Registrar atendimento</button></div>):<p className="muted">Nenhum agendamento disponível para registro.</p>}</section>:<div className="attendance-notice"><ClipboardPlus/><div><b>Registro reservado à Equipe Multiprofissional.</b><p>Direção e Coordenação acompanham os registros compartilhados, mas não registram atendimentos.</p></div></div>}
  {selected&&canRegister&&<form className="card attendance-form" onSubmit={save}><div className="form-heading"><div><h2>Registrar atendimento</h2><p className="muted"><b>{selected.students?.full_name}</b> · Agendamento de {dateFmt.format(new Date(selected.starts_at))}</p></div><button type="button" className="close-button" onClick={close}><X/></button></div><label>ESCUTA ATIVA – DEMANDA<textarea required value={demand} onChange={e=>setDemand(e.target.value)} rows={5}/><small>Registro sigiloso visível somente ao profissional autor deste atendimento.</small></label><label>ORIENTAÇÕES E ENCAMINHAMENTOS<textarea required value={guidance} onChange={e=>setGuidance(e.target.value)} rows={5}/><small>Informação institucional compartilhada com Direção, Coordenação, Psicologia e Serviço Social.</small></label><label>Continuidade do acompanhamento<select value={continuity} onChange={e=>setContinuity(e.target.value as ContinuityOption)}>{Object.entries(continuityOptions).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{continuity==="return_scheduled"&&<div className="appointment-form-grid"><label>Data do retorno<input required type="date" value={returnDate} onChange={e=>setReturnDate(e.target.value)}/></label><label>Horário<input type="time" value={returnTime} onChange={e=>setReturnTime(e.target.value)}/></label><label>Duração<select value={returnDuration} onChange={e=>setReturnDuration(e.target.value)}><option value="30">30 minutos</option><option value="50">50 minutos</option><option value="60">1 hora</option></select></label></div>}<div className="appointment-form-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?"Salvando…":"Salvar atendimento"}</button></div></form>}
  <section className="attendance-list"><h2>Histórico de atendimentos</h2>{records.length?records.map(r=><article className="card attendance-card" key={r.id}><div className="appointment-person"><UserRound/><div><strong>{r.students?.full_name}</strong><small>{r.students?.classes?.name||"Sem turma"} · {dateFmt.format(new Date(r.created_at))}</small></div></div><p><b>Orientações e Encaminhamentos:</b> {r.guidance_referrals}</p><small>Registrado por {r.profiles?.full_name||r.profiles?.email}</small></article>):<div className="card"><CalendarDays/><p className="muted">Nenhum atendimento registrado.</p></div>}</section>
 </AppShell>;
}
