"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { CheckCircle2, ClipboardPenLine, Clock3, Eye, FileText, Plus, Search, Trash2, UserRound, X } from "lucide-react";
import AppShell from "@/components/app-shell";
import { createClient } from "@/lib/supabase/client";
import "./reports.css";

type School = { id: string; name: string };
type Student = { id: string; full_name: string; classes: { name: string } | null };
type Teacher = { user_id: string; profiles: { full_name: string | null; email: string } | null };
type Report = { id: string; submitted_at: string | null; observed_period: string | null; attendance: string | null; participation: string | null; literacy: string | null; mathematics: string | null; behavior: string | null; strengths: string | null; difficulties: string | null; strategies: string | null; response_to_strategies: string | null; recent_changes: string | null; attention_note: string | null };
type RequestRow = { id: string; student_id: string; teacher_id: string; purpose: string; due_date: string | null; created_at: string; students: { full_name: string; classes: { name: string } | null } | null; profiles: { full_name: string | null; email: string } | null; teacher_reports: Report[] | null };

const emptyRequest = { student_id: "", teacher_id: "", purpose: "Apoiar o acompanhamento multiprofissional do estudante.", due_date: "" };
const emptyReport = { observed_period: "", attendance: "", participation: "", literacy: "", mathematics: "", behavior: "", strengths: "", difficulties: "", strategies: "", response_to_strategies: "", recent_changes: "", attention_note: "" };
const dateOnly = new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" });

export default function RelatoriosDocentes() {
  const [supabase] = useState(() => createClient()); const router = useRouter();
  const [email, setEmail] = useState(""); const [userId, setUserId] = useState(""); const [role, setRole] = useState(""); const [school, setSchool] = useState<School | null>(null);
  const [students, setStudents] = useState<Student[]>([]); const [teachers, setTeachers] = useState<Teacher[]>([]); const [requests, setRequests] = useState<RequestRow[]>([]);
  const [requestForm, setRequestForm] = useState(emptyRequest); const [reportForm, setReportForm] = useState(emptyReport); const [showRequest, setShowRequest] = useState(false); const [answering, setAnswering] = useState<RequestRow | null>(null); const [viewing, setViewing] = useState<RequestRow | null>(null);
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState("all"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    const { data: { user } } = await supabase.auth.getUser(); if (!user) { router.replace("/login"); return; }
    setEmail(user.email || ""); setUserId(user.id);
    const { data: membership } = await supabase.from("school_memberships").select("school_id,role,schools(id,name)").eq("user_id", user.id).eq("active", true).limit(1).single();
    const raw = membership?.schools as unknown; const current = (Array.isArray(raw) ? raw[0] : raw) as School | undefined; if (!current) return;
    setSchool(current); setRole(membership?.role || "");
    const [{ data: studentData }, { data: teacherData }, { data: requestData }] = await Promise.all([
      supabase.from("students").select("id,full_name,classes(name)").eq("school_id", current.id).eq("active", true).order("full_name"),
      supabase.from("school_memberships").select("user_id,profiles(full_name,email)").eq("school_id", current.id).eq("role", "teacher").eq("active", true),
      supabase.from("teacher_requests").select("id,student_id,teacher_id,purpose,due_date,created_at,students(full_name,classes(name)),profiles!teacher_requests_teacher_id_fkey(full_name,email),teacher_reports(id,submitted_at,observed_period,attendance,participation,literacy,mathematics,behavior,strengths,difficulties,strategies,response_to_strategies,recent_changes,attention_note)").eq("school_id", current.id).order("created_at", { ascending: false })
    ]);
    setStudents((studentData || []) as unknown as Student[]); setTeachers((teacherData || []) as unknown as Teacher[]); setRequests((requestData || []) as unknown as RequestRow[]);
  }, [router, supabase]);
  useEffect(() => { load(); }, [load]);

  const isTeacher = role === "teacher"; const completed = requests.filter(item => item.teacher_reports?.[0]?.submitted_at).length;
  const filtered = useMemo(() => { const term = search.trim().toLocaleLowerCase("pt-BR"); return requests.filter(item => { const done = Boolean(item.teacher_reports?.[0]?.submitted_at); const text = `${item.students?.full_name || ""} ${item.profiles?.full_name || ""} ${item.purpose}`.toLocaleLowerCase("pt-BR"); return (!term || text.includes(term)) && (filter === "all" || (filter === "completed" ? done : !done)); }); }, [filter, requests, search]);

  async function createRequest(event: FormEvent) { event.preventDefault(); if (!school || !userId) return; setBusy(true); setMessage(""); const { error } = await supabase.from("teacher_requests").insert({ school_id: school.id, student_id: requestForm.student_id, teacher_id: requestForm.teacher_id, requested_by: userId, purpose: requestForm.purpose.trim(), due_date: requestForm.due_date || null, status: "pending" }); setMessage(error ? "Não foi possível enviar a solicitação." : "Solicitação enviada ao professor."); if (!error) { setRequestForm(emptyRequest); setShowRequest(false); await load(); } setBusy(false); }
  async function deleteRequest(item: RequestRow) { if (!school || !confirm(`Excluir a solicitação sobre ${item.students?.full_name || "este aluno"}?`)) return; setBusy(true); const { error } = await supabase.from("teacher_requests").delete().eq("id", item.id).eq("school_id", school.id); setMessage(error ? "Não foi possível excluir a solicitação." : "Solicitação excluída."); if (!error) await load(); setBusy(false); }
  async function submitReport(event: FormEvent) { event.preventDefault(); if (!school || !answering) return; setBusy(true); setMessage(""); const { error } = await supabase.from("teacher_reports").insert({ request_id: answering.id, school_id: school.id, student_id: answering.student_id, teacher_id: userId, ...Object.fromEntries(Object.entries(reportForm).map(([key, value]) => [key, value.trim() || null])), submitted_at: new Date().toISOString() }); setMessage(error ? "Não foi possível enviar o relatório. Confira os campos e tente novamente." : "Relatório enviado com sucesso."); if (!error) { setAnswering(null); setReportForm(emptyReport); await load(); } setBusy(false); }

  if (!school) return <main className="loading">Carregando relatórios…</main>;
  const canRequest = students.length > 0 && teachers.length > 0;
  return <AppShell email={email}><header className="reports-header"><div><p className="eyebrow green">ACOMPANHAMENTO PEDAGÓGICO</p><h1>Relatórios docentes</h1><p className="muted">{isTeacher ? "Consulte e responda às solicitações destinadas a você." : "Solicite informações pedagógicas e acompanhe as respostas dos professores."}</p></div>{!isTeacher && <button className="primary-button" disabled={!canRequest} onClick={() => setShowRequest(true)}><Plus /> Solicitar relatório</button>}</header>
  {!isTeacher && !teachers.length && <div className="reports-warning"><UserRound /><div><b>Cadastre ao menos um professor na equipe.</b><p>Depois, será possível selecionar o docente responsável por cada relatório.</p></div><Link href="/dashboard/configuracoes">Configurar equipe</Link></div>}
  {!students.length && <div className="reports-warning"><UserRound /><div><b>Os alunos ainda não foram cadastrados.</b><p>Após a importação do PDF, eles ficarão disponíveis para as solicitações.</p></div><Link href="/dashboard/alunos">Alunos e turmas</Link></div>}
  {message && <div className="feedback">{message}</div>}
  {showRequest && <form className="card report-request-form" onSubmit={createRequest}><div className="form-heading"><div><h2>Solicitar relatório docente</h2><p className="muted">Escolha o aluno, o professor e informe a finalidade.</p></div><button type="button" className="close-button" onClick={() => setShowRequest(false)}><X /></button></div><div className="request-grid"><label>Aluno<select value={requestForm.student_id} onChange={e => setRequestForm({ ...requestForm, student_id: e.target.value })} required><option value="">Selecione o aluno</option>{students.map(student => <option value={student.id} key={student.id}>{student.full_name}{student.classes?.name ? ` — ${student.classes.name}` : ""}</option>)}</select></label><label>Professor(a)<select value={requestForm.teacher_id} onChange={e => setRequestForm({ ...requestForm, teacher_id: e.target.value })} required><option value="">Selecione o professor</option>{teachers.map(teacher => <option value={teacher.user_id} key={teacher.user_id}>{teacher.profiles?.full_name || teacher.profiles?.email}</option>)}</select></label><label>Prazo<input type="date" value={requestForm.due_date} onChange={e => setRequestForm({ ...requestForm, due_date: e.target.value })} /></label><label className="purpose-field">Finalidade da solicitação<textarea rows={3} value={requestForm.purpose} onChange={e => setRequestForm({ ...requestForm, purpose: e.target.value })} required /></label></div><div className="report-form-actions"><button type="button" className="secondary-button" onClick={() => setShowRequest(false)}>Cancelar</button><button disabled={busy}>{busy ? "Enviando…" : "Enviar solicitação"}</button></div></form>}
  {answering && <form className="card teacher-report-form" onSubmit={submitReport}><div className="form-heading"><div><h2>Relatório de {answering.students?.full_name || "aluno"}</h2><p className="muted">Finalidade: {answering.purpose}</p></div><button type="button" className="close-button" onClick={() => setAnswering(null)}><X /></button></div><div className="teacher-fields"><label>Período observado<input value={reportForm.observed_period} onChange={e => setReportForm({ ...reportForm, observed_period: e.target.value })} placeholder="Ex.: agosto e setembro de 2026" /></label><label>Frequência e pontualidade<textarea rows={3} value={reportForm.attendance} onChange={e => setReportForm({ ...reportForm, attendance: e.target.value })} /></label><label>Participação e realização das atividades<textarea rows={3} value={reportForm.participation} onChange={e => setReportForm({ ...reportForm, participation: e.target.value })} /></label><label>Leitura e escrita<textarea rows={3} value={reportForm.literacy} onChange={e => setReportForm({ ...reportForm, literacy: e.target.value })} /></label><label>Matemática<textarea rows={3} value={reportForm.mathematics} onChange={e => setReportForm({ ...reportForm, mathematics: e.target.value })} /></label><label>Comportamento e convivência<textarea rows={3} value={reportForm.behavior} onChange={e => setReportForm({ ...reportForm, behavior: e.target.value })} /></label><label>Pontos fortes<textarea rows={3} value={reportForm.strengths} onChange={e => setReportForm({ ...reportForm, strengths: e.target.value })} /></label><label>Dificuldades observadas<textarea rows={3} value={reportForm.difficulties} onChange={e => setReportForm({ ...reportForm, difficulties: e.target.value })} /></label><label>Estratégias já utilizadas<textarea rows={3} value={reportForm.strategies} onChange={e => setReportForm({ ...reportForm, strategies: e.target.value })} /></label><label>Resposta às estratégias<textarea rows={3} value={reportForm.response_to_strategies} onChange={e => setReportForm({ ...reportForm, response_to_strategies: e.target.value })} /></label><label>Mudanças recentes<textarea rows={3} value={reportForm.recent_changes} onChange={e => setReportForm({ ...reportForm, recent_changes: e.target.value })} /></label><label>Informação que exige atenção imediata<textarea rows={3} value={reportForm.attention_note} onChange={e => setReportForm({ ...reportForm, attention_note: e.target.value })} /></label></div><div className="report-form-actions"><button type="button" className="secondary-button" onClick={() => setAnswering(null)}>Cancelar</button><button disabled={busy}>{busy ? "Enviando…" : "Enviar relatório"}</button></div></form>}
  {viewing && viewing.teacher_reports?.[0] && <section className="card report-view"><div className="form-heading"><div><span className="completed-pill"><CheckCircle2 /> Relatório entregue</span><h2>{viewing.students?.full_name}</h2><p className="muted">Professor(a): {viewing.profiles?.full_name || viewing.profiles?.email}</p></div><button className="close-button" onClick={() => setViewing(null)}><X /></button></div><div className="report-answer-grid">{Object.entries({ "Período observado": viewing.teacher_reports[0].observed_period, "Frequência": viewing.teacher_reports[0].attendance, "Participação": viewing.teacher_reports[0].participation, "Leitura e escrita": viewing.teacher_reports[0].literacy, "Matemática": viewing.teacher_reports[0].mathematics, "Comportamento e convivência": viewing.teacher_reports[0].behavior, "Pontos fortes": viewing.teacher_reports[0].strengths, "Dificuldades": viewing.teacher_reports[0].difficulties, "Estratégias utilizadas": viewing.teacher_reports[0].strategies, "Resposta às estratégias": viewing.teacher_reports[0].response_to_strategies, "Mudanças recentes": viewing.teacher_reports[0].recent_changes, "Atenção imediata": viewing.teacher_reports[0].attention_note }).filter(([, value]) => value).map(([label, value]) => <div key={label}><b>{label}</b><p>{value}</p></div>)}</div></section>}
  <section className="reports-summary"><article><Clock3 /><div><strong>{requests.length - completed}</strong><span>relatórios pendentes</span></div></article><article><CheckCircle2 /><div><strong>{completed}</strong><span>relatórios entregues</span></div></article></section>
  <section className="card reports-card"><div className="reports-toolbar"><div><h2>{isTeacher ? "Minhas solicitações" : "Solicitações enviadas"}</h2><p className="muted">{filtered.length} {filtered.length === 1 ? "solicitação" : "solicitações"}</p></div><div className="reports-filters"><label className="search-box"><Search /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Pesquisar aluno ou professor" /></label><select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Todas</option><option value="pending">Pendentes</option><option value="completed">Entregues</option></select></div></div>{!filtered.length ? <div className="empty"><FileText /><h3>Nenhuma solicitação encontrada</h3><p>As solicitações de relatório aparecerão aqui.</p></div> : <div className="requests-list">{filtered.map(item => { const report = item.teacher_reports?.[0]; return <article key={item.id} className={report?.submitted_at ? "done" : "pending"}><div className="request-icon">{report?.submitted_at ? <CheckCircle2 /> : <ClipboardPenLine />}</div><div className="request-info"><div><span className={`request-status ${report?.submitted_at ? "done" : "pending"}`}>{report?.submitted_at ? "Entregue" : "Pendente"}</span><h3>{item.students?.full_name || "Aluno"}</h3><small>{item.students?.classes?.name || ""}</small></div><p>{item.purpose}</p><footer><span>Professor(a): {item.profiles?.full_name || item.profiles?.email}</span><span>Prazo: {item.due_date ? dateOnly.format(new Date(`${item.due_date}T12:00:00Z`)) : "não definido"}</span></footer></div><div className="request-actions">{report?.submitted_at ? <button onClick={() => setViewing(item)}><Eye /> Ver relatório</button> : isTeacher ? <button onClick={() => { setAnswering(item); setReportForm(emptyReport); }}><ClipboardPenLine /> Responder</button> : <button className="delete" onClick={() => deleteRequest(item)} title="Excluir"><Trash2 /></button>}</div></article>; })}</div>}</section></AppShell>;
}
