create extension if not exists pgcrypto;
create type public.app_role as enum ('matrix_admin','school_admin','director','coordinator','psychologist','social_worker','teacher');
create type public.referral_status as enum ('received','triage','awaiting_schedule','scheduled','in_follow_up','awaiting_school_action','external_referral','completed','reopened');
create type public.priority_level as enum ('routine','attention','urgent');
create type public.note_type as enum ('shared','confidential_psychology','confidential_social');
create type public.subscription_status as enum ('pilot','demo','onboarding','trial','active','overdue','suspended','cancelled');

create table public.schools (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, city text, state char(2), active boolean not null default true, subscription_status public.subscription_status not null default 'pilot', created_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email text not null, platform_admin boolean not null default false, active boolean not null default true, created_at timestamptz not null default now());
create table public.school_memberships (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role public.app_role not null, active boolean not null default true, unique(school_id,user_id));
create table public.classes (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, school_year integer not null, active boolean not null default true, unique(school_id,name,school_year));
create table public.teacher_class_assignments (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, teacher_user_id uuid not null references public.profiles(id) on delete cascade, class_id uuid not null references public.classes(id) on delete cascade, unique(teacher_user_id,class_id));
create table public.students (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, class_id uuid references public.classes(id) on delete set null, full_name text not null, birth_date date, guardian_name text, guardian_phone text, active boolean not null default true, created_at timestamptz not null default now());
create table public.referrals (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, created_by uuid not null references public.profiles(id), assigned_to uuid references public.profiles(id), reason_summary text not null, priority public.priority_level not null default 'routine', status public.referral_status not null default 'received', school_actions text, due_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.appointments (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, referral_id uuid references public.referrals(id) on delete set null, professional_id uuid not null references public.profiles(id), starts_at timestamptz not null, ends_at timestamptz not null, kind text not null, status text not null default 'scheduled', location text, created_at timestamptz not null default now(), check(ends_at > starts_at));
create table public.case_notes (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, referral_id uuid references public.referrals(id) on delete set null, author_id uuid not null references public.profiles(id), note_type public.note_type not null, content text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.teacher_requests (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, teacher_id uuid not null references public.profiles(id), requested_by uuid not null references public.profiles(id), purpose text not null, due_date date, status text not null default 'pending', created_at timestamptz not null default now());
create table public.teacher_reports (id uuid primary key default gen_random_uuid(), request_id uuid not null unique references public.teacher_requests(id) on delete cascade, school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, teacher_id uuid not null references public.profiles(id), observed_period text, attendance text, participation text, peer_interaction text, adult_interaction text, communication text, autonomy text, attention text, task_completion text, literacy text, mathematics text, behavior text, frustration_response text, full_day_stay text, strengths text, difficulties text, strategies text, response_to_strategies text, recent_changes text, attention_note text, submitted_at timestamptz, created_at timestamptz not null default now());
create table public.audit_logs (id bigint generated always as identity primary key, school_id uuid references public.schools(id) on delete set null, user_id uuid references public.profiles(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());

create schema if not exists private;
create or replace function private.is_platform_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.platform_admin and p.active) $$;
create or replace function private.has_school_role(sid uuid, roles public.app_role[]) returns boolean language sql stable security definer set search_path='' as $$ select private.is_platform_admin() or exists(select 1 from public.school_memberships m where m.school_id=sid and m.user_id=auth.uid() and m.active and m.role=any(roles)) $$;
create or replace function private.is_school_member(sid uuid) returns boolean language sql stable security definer set search_path='' as $$ select private.is_platform_admin() or exists(select 1 from public.school_memberships m where m.school_id=sid and m.user_id=auth.uid() and m.active) $$;
create or replace function private.is_teacher_for_student(student uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.students s join public.teacher_class_assignments t on t.class_id=s.class_id and t.school_id=s.school_id where s.id=student and t.teacher_user_id=auth.uid()) $$;
revoke all on schema private from public; grant usage on schema private to authenticated; grant execute on all functions in schema private to authenticated;

alter table public.schools enable row level security; alter table public.profiles enable row level security; alter table public.school_memberships enable row level security; alter table public.classes enable row level security; alter table public.teacher_class_assignments enable row level security; alter table public.students enable row level security; alter table public.referrals enable row level security; alter table public.appointments enable row level security; alter table public.case_notes enable row level security; alter table public.teacher_requests enable row level security; alter table public.teacher_reports enable row level security; alter table public.audit_logs enable row level security;

create policy schools_read on public.schools for select to authenticated using(private.is_school_member(id));
create policy profiles_self_or_colleague on public.profiles for select to authenticated using(id=auth.uid() or private.is_platform_admin() or exists(select 1 from public.school_memberships mine join public.school_memberships theirs on theirs.school_id=mine.school_id where mine.user_id=auth.uid() and theirs.user_id=profiles.id and mine.active and theirs.active));
create policy memberships_read on public.school_memberships for select to authenticated using(user_id=auth.uid() or private.has_school_role(school_id,array['matrix_admin','school_admin','director']::public.app_role[]));
create policy classes_read on public.classes for select to authenticated using(private.has_school_role(school_id,array['matrix_admin','school_admin','director','coordinator','psychologist','social_worker']::public.app_role[]) or exists(select 1 from public.teacher_class_assignments t where t.class_id=classes.id and t.teacher_user_id=auth.uid()));
create policy assignments_read on public.teacher_class_assignments for select to authenticated using(teacher_user_id=auth.uid() or private.has_school_role(school_id,array['matrix_admin','school_admin','director','coordinator']::public.app_role[]));
create policy students_read on public.students for select to authenticated using(private.has_school_role(school_id,array['matrix_admin','school_admin','director','coordinator','psychologist','social_worker']::public.app_role[]) or private.is_teacher_for_student(id));
create policy staff_manage_students on public.students for all to authenticated using(private.has_school_role(school_id,array['matrix_admin','school_admin','director','coordinator']::public.app_role[])) with check(private.has_school_role(school_id,array['matrix_admin','school_admin','director','coordinator']::public.app_role[]));
create policy staff_referrals on public.referrals for all to authenticated using(private.has_school_role(school_id,array['matrix_admin','school_admin','director','coordinator','psychologist','social_worker']::public.app_role[])) with check(private.has_school_role(school_id,array['matrix_admin','school_admin','director','coordinator','psychologist','social_worker']::public.app_role[]));
create policy staff_appointments on public.appointments for all to authenticated using(private.has_school_role(school_id,array['school_admin','director','coordinator','psychologist','social_worker']::public.app_role[])) with check(private.has_school_role(school_id,array['school_admin','director','coordinator','psychologist','social_worker']::public.app_role[]));
create policy notes_read on public.case_notes for select to authenticated using((note_type='shared' and private.has_school_role(school_id,array['school_admin','director','coordinator','psychologist','social_worker']::public.app_role[])) or (note_type='confidential_psychology' and author_id=auth.uid() and private.has_school_role(school_id,array['psychologist']::public.app_role[])) or (note_type='confidential_social' and author_id=auth.uid() and private.has_school_role(school_id,array['social_worker']::public.app_role[])));
create policy notes_insert on public.case_notes for insert to authenticated with check(author_id=auth.uid() and ((note_type='shared' and private.has_school_role(school_id,array['school_admin','director','coordinator','psychologist','social_worker']::public.app_role[])) or (note_type='confidential_psychology' and private.has_school_role(school_id,array['psychologist']::public.app_role[])) or (note_type='confidential_social' and private.has_school_role(school_id,array['social_worker']::public.app_role[]))));
create policy own_notes_update on public.case_notes for update to authenticated using(author_id=auth.uid()) with check(author_id=auth.uid());
create policy teacher_requests_read on public.teacher_requests for select to authenticated using(teacher_id=auth.uid() or private.has_school_role(school_id,array['school_admin','director','coordinator','psychologist','social_worker']::public.app_role[]));
create policy staff_requests_manage on public.teacher_requests for all to authenticated using(private.has_school_role(school_id,array['school_admin','director','coordinator','psychologist','social_worker']::public.app_role[])) with check(private.has_school_role(school_id,array['school_admin','director','coordinator','psychologist','social_worker']::public.app_role[]));
create policy reports_read on public.teacher_reports for select to authenticated using(teacher_id=auth.uid() or private.has_school_role(school_id,array['school_admin','director','coordinator','psychologist','social_worker']::public.app_role[]));
create policy teacher_reports_insert on public.teacher_reports for insert to authenticated with check(teacher_id=auth.uid() and private.is_teacher_for_student(student_id));
create policy teacher_reports_update on public.teacher_reports for update to authenticated using(teacher_id=auth.uid() and submitted_at is null) with check(teacher_id=auth.uid());
create policy audit_admin_read on public.audit_logs for select to authenticated using(school_id is not null and private.has_school_role(school_id,array['matrix_admin','school_admin','director']::public.app_role[]));

create index memberships_user_school_idx on public.school_memberships(user_id,school_id) where active;
create index students_school_class_idx on public.students(school_id,class_id) where active;
create index referrals_school_status_idx on public.referrals(school_id,status,created_at desc);
create index appointments_school_start_idx on public.appointments(school_id,starts_at);
create index notes_student_type_idx on public.case_notes(student_id,note_type,created_at desc);

insert into public.schools(name,slug,city,state,subscription_status) values('CAIC','caic','',null,'pilot') on conflict(slug) do nothing;
